\ ww.f
\ FORGET 9W
: WW BL WORD 9 >R
  CONTEXT @
  BEGIN ?DUP
  WHILE \ CR .S CR OVER COUNT TYPE DUP .ID 
     2DUP INSTR
     IF DUP DUP CR R@ . SPACE 4 .R DUP 2/ . DUP IC@ 3 .R .ID
        R> 1- ?DUP
        IF ELSE DROP R> 2DROP EXIT
        THEN
        >R
     THEN >LINK I@
  REPEAT R> 2DROP
;
